VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/centos7"
  config.vm.hostname = "nodejs.test"
  config.vm.network :private_network,
      :ip => "192.168.121.3",
      :libvirt_network_name => "vagrant"

  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider :libvirt do |v|
    v.memory = 512
  end
  config.vm.provision "file", source: "./public.pub", destination: "~/.ssh/public.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/public.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  
  # Ansible provisioner.
  #config.vm.provision :ansible do |ansible|
  #  ansible.playbook = "provisioning/nodejs.yml"
  #end
end
